### PR TITLE
more CI test environments and completing update for new NetworkX API

### PR DESCRIPTION
**Pull request by slivingston**
This pull request (PR) includes changes from the [branch completed_update_to_networkx_2](https://github.com/tulip-control/tulip-control/tree/completed_update_to_networkx_2) and the temporary branch `tmp-debug-travisci-addition`. I cherry-picked (i.e., `git cherry-pick`) where feasible with the goal of preserving original commit messages and giving credit to the author of respective commits.

This PR contributes by
1. completing changes to use the new NetworkX API (and therefore, building on prior work in PR #220),
2. updating the CI configuration, in particular to include test environments for Python 3.7 and 3.8
3. various small changes, e.g., refactoring code given that `assert` is a statement, not a function.

### CODE REVIEW

**Comment by murrayrm** [comment]
Is there a reason why CI tests didn't run?

**Comment by slivingston** [comment]
The previous commit contains the text "[ci skip]", which prevents a CI build from starting. I did so because that commit only involved documentation changes. Notice that [CI tests were performed](https://travis-ci.org/tulip-control/tulip-control/builds/654204624) for the preceding commit.

**Comment by slivingston** [comment]
Thanks to @johnyf for notifying me of a regression where I accidentally removed part of the changeset a560445870401f7da3add6ca0e6ae0f39cff1e9b. Accordingly, I edited and force-pushed the branch of this PR.

**Comment by slivingston** [comment]
I added an assertion to the gr1c tests to prevent the regression [mentioned above](https://github.com/tulip-control/tulip-control/pull/226#issuecomment-590546004).

**Comment by johnyf** [comment]
Thank you @slivingston for preparing this pull request. I think the changes are ready to be merged.

**Pull request merged**
