### PR TITLE
Find controller lp

### PR DESCRIPTION
**Pull request by necozay**
Addresses the issue #154 .

### CODE REVIEW

**Comment by johnyf** [comment]
Thanks, these commits will be rebased upon merging.

**Comment by johnyf** [comment]
How would this change better be described in the changelog? (A draft can be found in a4f4cc330ca8fbad6061ee610d003667da595a39).

Why was the quadratic cost completely removed? Can it not be available whenever `cvxopt` is available, as commented here: https://github.com/tulip-control/tulip-control/issues/154#issuecomment-257048844? The dependencies will remain the same (`cvxopt` absent from `install_requires` in `setup.py`, and present in `requirements.txt`, as an optional dependency). If the 2-norm option can be kept, then should I simply copy the [old code](https://github.com/tulip-control/tulip-control/commit/52ba38a89fb128e29a4bd7e9eef002db50f8f345#diff-db73a44c4631fa5fc7c04bff0f7d729aL401) to the case `ord == 2`?

Why was the function renamed to [`get_input_helper_LP`](https://github.com/tulip-control/tulip-control/commit/52ba38a89fb128e29a4bd7e9eef002db50f8f345#diff-db73a44c4631fa5fc7c04bff0f7d729aR332)? It includes the case `ord == 2`, so it is not only linear programming (even though it raises an error for `ord == 2`). I support keeping the name `get_input_helper` (if renamed, following PEP8 it would be `get_input_helper_lp`).

The newly introduced keyword `ord` for the function `get_input_helper` precedes the existing keyword `closed_loop`. It will break existing callers. Is this ordering of keyword intentional? Does it based on relative importance of keyword arguments? (The latter is a good reason for placing it earlier.)

PEP8 [recommends](https://www.python.org/dev/peps/pep-0008/#function-and-method-arguments) ([here too](https://www.python.org/dev/peps/pep-0008/#designing-for-inheritance)) to avoid abbreviations or corrupted spelling, when feasible. The name `ord` is short, but `order` is not too long, and self-documenting (to some degree). I would recommend using `order`, unless there is some specific reason for choosing `ord` (for example, uniformity with `numpy`'s API?)

There are two collections of commits above. Rebasing the later ones (with some conflict resolution) yields a patch clean of whitespace changes, which appears to differ from the rebase of the older ones only by 43e1e9b75b31afcec8fc989c2b1cf3c70854e72d, which I copied. I kept `cvxopt`, until item about `ord == 2` is resolved. It would help to confirm whether 52ba38a89fb128e29a4bd7e9eef002db50f8f345 is the intended result.

Main messages from `pep8 tulip/abstract/find_controller.py`:
- E231 missing whitespace after ','
- E101 indentation contains mixed spaces and tabs
- W191 indentation contains tabs
- E265 block comment should start with '# '
- E111 indentation is not a multiple of four

**Comment by necozay** [comment]
Fine to put back the QP inside ``ord == 2``.  I would suggest one change for consistency though. I prefer ``R^TR`` and ``Q^TQ`` to be used in the QP to make it consistent with the other norms, i.e., ``||Rx||_ord``. This changes the meaning of ``R`` in earlier versions.

I agree with keeping the function name ``get_input_helper``.

I think `R`, `r`, `Q` and `ord` are all related to the cost function so it makes sense to have them together in the signature of `get_input_helper`. I suggest we make that change in the signature of `get_input` as well.

`ord` is used for uniformity with `numpy`'s API. I prefer to keep it. Otherwise, something like `norm_type` would be more informative.

**Comment by johnyf** [comment]
I applied these changes as of 5e75e6dddfa3b2234f86cc472ab08e246109166a.
Placed `ord` after `R, r, Q` in args, `autopep8`, and some misc modifications to `find_controller`.

From what I understand (correct me if wrong) by a comparison, the QP:

```
old: x^T R x
new: |R x|^2 = (R x)^T (R x) = x^T (R^T R) x
```

So, to use the old code with the new input, I "symmetrize" the matrices `Q` and `R`, by using `Q2 = Q^T Q` and `R2 = R^T R` in place of `Q, R` as input to the old code. The addition of `mid_weight` is left untouched, and the same for all norms. Also, `0.5 r` is used, because `cvxopt` multiplies the quadratic term `x^T P x` with `0.5` and the docstring says `|Rx|_{ord} + |Qu|_{ord} + r'x + mid_weight * |xc - x(0)|_{ord}`.

Also, based on [this comment](https://github.com/tulip-control/tulip-control/issues/154#issuecomment-258577005), should we `assert closed_loop is False`?

The example `continuous_with_simulation.py` says: "WARNING:tulip.abstract.discretization:	 too small: si \ Pre(sj), so not reached it". Noted in case we should change something (probably not).

Also, except for the example, there are no tests for the new code. I think that when the implementation is completed (`closed_loop = True`) and the issues mentioned [here](https://github.com/tulip-control/tulip-control/issues/162#issuecomment-239633913) addressed, then tests can be added.

Note: This PR includes the simulation code from #146.

Besides the minor questions above, I consider this PR ready for merging.

**Comment by johnyf** [comment]
Regarding tests, they are the subject of #166.

**Comment by necozay** [comment]
QP interpretation is right. I was not aware of `cvxopt`s 1/2 factor but it makes sense.

I decided that it would make more sense to address ``closed_loop = True`` case separately. The current version is not any different than what ``closed_loop`` has been implementing up to now (modulo solver change but it should not affect feasibility). The code should still work as before so maybe no need to add an assertion. On the other hand, I think the latest changes in abstraction 0c8f8b8651b9d6e66be509ca3981893f2696eab7 might have introduced additional inconsistencies because I see ``closed_loop = True`` case failing more often. Again it is independent of this PRs goal. A warning about a potential bug might be useful though.

For the warning in the example `continuous_with_simulation.py`, see [this](https://github.com/tulip-control/polytope/issues/30) issue of polytope. If you try to run it 7-8 times, it should go through.

**Comment by necozay** [comment]
If you have any thoughts on how to avoid "WARNING:tulip.abstract.discretization: too small: si \ Pre(sj), so not reached it" without updating `polytope` and enforcing a change in `polytope` version, let me know. Otherwise discretization fails sometimes for this example and maybe we should include a warning somewhere in the example docstrings until `polytope` is fixed

**Comment by necozay** [comment]
I was trying to refer to the error message: `raise Exception("iterative_hull: "
Exception: iterative_hull: could not find starting simplex` in my two previous comments not the warning coming from `discretization`....

**Comment by johnyf** [comment]
Thanks for the clarification, the example printed the warning a couple of times during abstraction, but it completed. I did not encounter this `Exception` in the example, but I will think about it.

**Comment by johnyf** [comment]
Merged as 411aa2d9aeb886b1d74ca135f245ac268fa03d0e. A warning is now logged if `closed_loop = True` is given to `get_input`.

I agree for the implementation for the case `closed_loop = True` to be addressed outside the scope of this PR.

For posterity, the 1/2 factor in QP in `cvxopt` is mentioned [here](http://cvxopt.org/userguide/coneprog.html#quadratic-programming).

Given that the exception was not observed here, let's investigate it further in the relevant issue of `polytope`. I think that it is fine to make modifications there, given also that the next `polytope` release will be cut soon.

**Comment by johnyf** [comment]
This PR makes `tulip` deployable in absence of `cvxopt`. This has been a long awaited objective, in particular:

- it completes the modifications outlined here: https://github.com/tulip-control/tulip-control/issues/48#issuecomment-41227876
- `cvxopt` was made optional in #122, but still required for `find_controller`. Now it is entirely optional, unless a quadratic cost is desired when designing a controller for the continuous state.

**Pull request closed without merging**
