### PR TITLE
Bug fix in discretize.py

### PR DESCRIPTION
**Pull request by ajwagen**
pwa.py failed when plotting is set to False.

### CODE REVIEW

**Comment by johnyf** [comment]
Thanks.

**Comment by slivingston** [comment]
@ajwagen We want to add your name as a contributor in [AUTHORS](https://github.com/tulip-control/tulip-control/blob/9a7b092df1e9805cfcd91f56403132688f5fb282/AUTHORS). Can you tell us how you want it to be listed? E.g., would it be "Andrew Wagenmaker" or "ajwagen"? Your commit message lists your name as "ajwagen".

In case you want to change your author name used in commits, you can change your `user.name` Git config value. Instructions can be found, e.g., at <https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup#Your-Identity>.

**Comment by johnyf** [comment]
We may also want to introduce a policy of asking new contributors upon their opening of a pull request.

**Comment by slivingston** [comment]
At <https://github.com/tulip-control/tulip-control/wiki/Draft-about-workflows-for-accepting-contributions> I collected references to several guides from other projects that might be useful in establishing a policy here.

**Comment by ajwagen** [comment]
Could you list it as 'Andrew Wagenmaker'? Thanks.

**Comment by johnyf** [comment]
Addressed in 8d4ceb9c662392ce5d687d884d49e8f0a555cd81.

**Pull request merged**
